import Head from "next/head";

export default function Layout({ children, isLoggedIn }) {
	return (
		<>
			<Head>
				<title>[REIM inc.] | Reim inc. reimbursement portal</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			{/* Create header with conditional render logout button */}
			{children}
		</>
	);
}
