import Head from "next/head";
import { ToastContainer, toast } from "react-toastify";
import { Text, Button } from "@geist-ui/core";
import { useRouter } from "next/router";

export default function Layout({ children, isLoggedIn }) {
	const router = useRouter();
	const logout = () => {
		fetch("/api/logout").then((res) => {
			if (res.status === 200) {
				router.push("/login");
			} else {
				toast.error(
					"Looks like an error occured while logging out. Please try again."
				);
			}
		});
	};
	return (
		<>
			<Head>
				<title>[Reim inc.] Reimbursement Portal</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
			</Head>
			<header className="header">
				<div className="container flex">
					<Text h3>[Reim inc.] </Text>
					{isLoggedIn && (
						<Button
							onClick={() => logout()}
							shadow
							type="secondary">
							Logout
						</Button>
					)}
				</div>
			</header>
			<ToastContainer />
			{children}
		</>
	);
}
